// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutritionApp.Data.Data;

#nullable disable

namespace NutritionApp.Data.Migrations
{
    [DbContext(typeof(NutritionContext))]
    [Migration("20250215195254_Initial_Data")]
    partial class Initial_Data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NutritionApp.Data.Models.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Calories")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("NutritionApp.Data.Models.StorageItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("StorageItems");
                });

            modelBuilder.Entity("NutritionApp.Data.Models.FoodItem", b =>
                {
                    b.OwnsOne("NutritionApp.Data.Models.Carbohydrates", "Carbohydrates", b1 =>
                        {
                            b1.Property<int>("FoodItemId")
                                .HasColumnType("int");

                            b1.Property<decimal>("ComplexCarbs")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<decimal>("Fiber")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<decimal>("Sugar")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<decimal>("Total")
                                .HasColumnType("decimal(65,30)");

                            b1.HasKey("FoodItemId");

                            b1.ToTable("FoodItems");

                            b1.WithOwner()
                                .HasForeignKey("FoodItemId");
                        });

                    b.OwnsOne("NutritionApp.Data.Models.Fats", "Fats", b1 =>
                        {
                            b1.Property<int>("FoodItemId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Omega3")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<decimal>("Omega6")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<decimal>("Total")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<decimal>("TransFat")
                                .HasColumnType("decimal(65,30)");

                            b1.HasKey("FoodItemId");

                            b1.ToTable("FoodItems");

                            b1.WithOwner()
                                .HasForeignKey("FoodItemId");
                        });

                    b.OwnsOne("NutritionApp.Data.Models.Proteins", "Proteins", b1 =>
                        {
                            b1.Property<int>("FoodItemId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Total")
                                .HasColumnType("decimal(65,30)");

                            b1.HasKey("FoodItemId");

                            b1.ToTable("FoodItems");

                            b1.WithOwner()
                                .HasForeignKey("FoodItemId");
                        });

                    b.Navigation("Carbohydrates")
                        .IsRequired();

                    b.Navigation("Fats")
                        .IsRequired();

                    b.Navigation("Proteins")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
